### ISSUE TITLE
Kommentieren nicht möglich (Link?)

### ISSUE THREAD

**Issue by chibbs** [Sinnaj94/HaengemattenApp#9]

**Comment by chibbs** [comment]
Kommentieren geht jetzt, aber das Fenster mit den Kommentaren ist so winzig, da sieht man nix. Und löschen und editieren geht noch nicht...

![grafik](https://user-images.githubusercontent.com/13432215/51586787-e11f2b00-1ede-11e9-9715-7af900bc9486.png)

![grafik](https://user-images.githubusercontent.com/13432215/51586796-e8463900-1ede-11e9-995f-a61bfcbcd065.png)

**Comment by Sinnaj94** [comment]
Modal dialog oder Popup größer machen?
